spin_manifest_version = "1"
authors = ["Steven Lotito <steven.lotito+gh@gmail.com>"]
description = "Hello world using Spin"
name = "hello_rust"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello-rust"
source = "target/wasm32-wasi/release/hello_rust.wasm"
allowed_http_hosts = ["172.30.1.16"]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
